apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: kustomize-tutorial
build:
  artifacts:
    - image: docker.io/nnsay/rest-nodejs
      context: app/nodeapi
      docker:
        dockerfile: Dockerfile
        # noCache: true
        # cliFlags:
        #   - --no-cache
  local:
    push: true
    # useDockerCLI: true
  # tagPolicy:
  #   gitCommit:
  #     prefix: dev
manifests:
  kustomize:
    paths:
      - .
profiles:
  - name: knative
    manifests:
      kustomize:
        paths:
          - knative
